effectifelevenouveaupremierannee_edit:
    path:     /modifier
    defaults: { _controller: "SiseCoreBundle:EffectifeleveNouveaupremierannee:edit" }

effectifelevenouveaupremierannee_list:
    path:     /list
    defaults: { _controller: "SiseCoreBundle:EffectifeleveNouveaupremierannee:list" }

effectifelevenouveaupremierannee_update:
    path:     /{codeetab}/{codetypeetab}/Modif
    defaults: { _controller: "SiseCoreBundle:EffectifeleveNouveaupremierannee:update" }
    requirements: { _method: post|put }
effectifelevenouveaupremierannee_form:
    path:     /form
    defaults: { _controller: "SiseCoreBundle:EffectifeleveNouveaupremierannee:item" }
effectifelevenouveaupremierannee_relatedLists:
    path:     /relatedLists
    defaults: { _controller: "SiseCoreBundle:EffectifeleveNouveaupremierannee:relatedLists" }
effectifelevenouveaupremierannee_deleteItem:
    path:     /deleteItem
    defaults: { _controller: "SiseCoreBundle:EffectifeleveNouveaupremierannee:deleteItem" }
    requirements: { _method: post|delete }