effectiveenseignentgradediscipline_list:
    path:     /list
    defaults: { _controller: "SiseCoreBundle:EffectiveenseignentGradediscipline:index" }

effectiveenseignentgradediscipline_edit:
    path:     /edit
    defaults: { _controller: "SiseCoreBundle:EffectiveenseignentGradediscipline:edit" }

effectiveenseignentgradediscipline_update:
    path:     /update
    defaults: { _controller: "SiseCoreBundle:EffectiveenseignentGradediscipline:update" }
    requirements: { _method: post|put }
