effectifelevelisteelevedeplacerversautreetablissement_edit:
    path:     /modifier
    defaults: { _controller: "SiseCoreBundle:EffectifeleveListeelevedeplacerversautreetablissement:edit" }

effectifelevelisteelevedeplacerversautreetablissement_list:
    path:     /list
    defaults: { _controller: "SiseCoreBundle:EffectifeleveListeelevedeplacerversautreetablissement:list" }

effectifelevelisteelevedeplacerversautreetablissement_update:
    path:     /{codeetab}/{codetypeetab}/Modif
    defaults: { _controller: "SiseCoreBundle:EffectifeleveListeelevedeplacerversautreetablissement:update" }
    requirements: { _method: post|put }
effectifelevelisteelevedeplacerversautreetablissement_form:
    path:     /form
    defaults: { _controller: "SiseCoreBundle:EffectifeleveListeelevedeplacerversautreetablissement:item" }
effectifelevelisteelevedeplacerversautreetablissement_deleteItem:
    path:     /deleteItem
    defaults: { _controller: "SiseCoreBundle:EffectifeleveListeelevedeplacerversautreetablissement:deleteItem" }
    requirements: { _method: post|delete }