effectifelevegenreanneenaissance_edit:
    path:     /modifier
    defaults: { _controller: "SiseCoreBundle:EffectifeleveGenreAnneenaissance:edit" }

effectifelevegenreanneenaissance_list:
    path:     /list
    defaults: { _controller: "SiseCoreBundle:EffectifeleveGenreAnneenaissance:list" }

effectifelevegenreanneenaissance_update:
    path:     /{codeetab}/{codetypeetab}/Modif
    defaults: { _controller: "SiseCoreBundle:EffectifeleveGenreAnneenaissance:update" }
    requirements: { _method: post|put|get }

effectifelevegenreanneenaissance_delete:
    path:     /{id}/delete
    defaults: { _controller: "SiseCoreBundle:EffectifeleveGenreAnneenaissance:delete" }
    requirements: { _method: post|delete }
