effectifelevelisteeleveemmenagerdesonetablissement_edit:
    path:     /modifier
    defaults: { _controller: "SiseCoreBundle:EffectifeleveListeeleveemmenagerdesonetablissement:edit" }

effectifelevelisteeleveemmenagerdesonetablissement_list:
    path:     /list
    defaults: { _controller: "SiseCoreBundle:EffectifeleveListeeleveemmenagerdesonetablissement:list" }

effectifelevelisteeleveemmenagerdesonetablissement_update:
    path:     /{codeetab}/{codetypeetab}/Modif
    defaults: { _controller: "SiseCoreBundle:EffectifeleveListeeleveemmenagerdesonetablissement:update" }
    requirements: { _method: post|put }
effectifelevelisteeleveemmenagerdesonetablissement_form:
    path:     /form
    defaults: { _controller: "SiseCoreBundle:EffectifeleveListeeleveemmenagerdesonetablissement:item" }
effectifelevelisteeleveemmenagerdesonetablissement_deleteItem:
    path:     /deleteItem
    defaults: { _controller: "SiseCoreBundle:EffectifeleveListeeleveemmenagerdesonetablissement:deleteItem" }
    requirements: { _method: post|delete }