effectiveenseignentlisteenseignenteducationtechnique_edit:
    path:     /Modifier
    defaults: { _controller: "SiseCoreBundle:EffectiveenseignentListeenseignentEducationtechnique:edit" }

effectiveenseignentlisteenseignenteducationtechnique_list:
    path:     /list
    defaults: { _controller: "SiseCoreBundle:EffectiveenseignentListeenseignentEducationtechnique:list" }

effectiveenseignentlisteenseignenteducationtechnique_update:
    path:     /{codeetab}/{codetypeetab}/Modif
    defaults: { _controller: "SiseCoreBundle:EffectiveenseignentListeenseignentEducationtechnique:update" }
    requirements: { _method: post|put }
effectiveenseignentlisteenseignenteducationtechnique_form:
    path:     /form
    defaults: { _controller: "SiseCoreBundle:EffectiveenseignentListeenseignentEducationtechnique:item" }
effectiveenseignentlisteenseignenteducationtechnique_deleteItem:
    path:     /deleteItem
    defaults: { _controller: "SiseCoreBundle:EffectiveenseignentListeenseignentEducationtechnique:deleteItem" }
    requirements: { _method: post|delete }