effectiveenseignentlisteenseignentheureautreetablissement_edit:
    path:     /Modifier
    defaults: { _controller: "SiseCoreBundle:EffectiveenseignentListeenseignentheureautreetablissement:edit" }

effectiveenseignentlisteenseignentheureautreetablissement_list:
    path:     /list
    defaults: { _controller: "SiseCoreBundle:EffectiveenseignentListeenseignentheureautreetablissement:list" }

effectiveenseignentlisteenseignentheureautreetablissement_update:
    path:     /{codeetab}/{codetypeetab}/Modif
    defaults: { _controller: "SiseCoreBundle:EffectiveenseignentListeenseignentheureautreetablissement:update" }
    requirements: { _method: post|put }
effectiveenseignentlisteenseignentheureautreetablissement_form:
    path:     /form
    defaults: { _controller: "SiseCoreBundle:EffectiveenseignentListeenseignentheureautreetablissement:item" }
effectiveenseignentlisteenseignentheureautreetablissement_deleteItem:
    path:     /deleteItem
    defaults: { _controller: "SiseCoreBundle:EffectiveenseignentListeenseignentheureautreetablissement:deleteItem" }
    requirements: { _method: post|delete }