effectiveenseignentlisteenseignentheureautreetablissement_list:
    path:     /list
    defaults: { _controller: "SiseCoreBundle:EffectiveenseignentListeenseignentheureautreetablissement:index" }

effectiveenseignentlisteenseignentheureautreetablissement_show:
    path:     /{id}/show
    defaults: { _controller: "SiseCoreBundle:EffectiveenseignentListeenseignentheureautreetablissement:show" }

effectiveenseignentlisteenseignentheureautreetablissement_new:
    path:     /new
    defaults: { _controller: "SiseCoreBundle:EffectiveenseignentListeenseignentheureautreetablissement:new" }

effectiveenseignentlisteenseignentheureautreetablissement_create:
    path:     /create
    defaults: { _controller: "SiseCoreBundle:EffectiveenseignentListeenseignentheureautreetablissement:create" }
    requirements: { _method: post }

effectiveenseignentlisteenseignentheureautreetablissement_edit:
    path:     /edit
    defaults: { _controller: "SiseCoreBundle:EffectiveenseignentListeenseignentheureautreetablissement:edit" }

effectiveenseignentlisteenseignentheureautreetablissement_update:
    path:     /{id}/update
    defaults: { _controller: "SiseCoreBundle:EffectiveenseignentListeenseignentheureautreetablissement:update" }
    requirements: { _method: post|put }

effectiveenseignentlisteenseignentheureautreetablissement_delete:
    path:     /{id}/delete
    defaults: { _controller: "SiseCoreBundle:EffectiveenseignentListeenseignentheureautreetablissement:delete" }
    requirements: { _method: post|delete }
