effectiveenseignentlisteenseignenttypeenseignement_edit:
    path:     /modifier
    defaults: { _controller: "SiseCoreBundle:EffectiveenseignentListeenseignentTypeenseignement:edit" }

effectiveenseignentlisteenseignenttypeenseignement_list:
    path:     /list
    defaults: { _controller: "SiseCoreBundle:EffectiveenseignentListeenseignentTypeenseignement:list" }

effectiveenseignentlisteenseignenttypeenseignement_update:
    path:     /{codeetab}/{codetypeetab}/Modif
    defaults: { _controller: "SiseCoreBundle:EffectiveenseignentListeenseignentTypeenseignement:update" }
    requirements: { _method: post|put }
effectiveenseignentlisteenseignenttypeenseignement_form:
    path:     /form
    defaults: { _controller: "SiseCoreBundle:EffectiveenseignentListeenseignentTypeenseignement:item" }
effectiveenseignentlisteenseignenttypeenseignement_deleteItem:
    path:     /deleteItem
    defaults: { _controller: "SiseCoreBundle:EffectiveenseignentListeenseignentTypeenseignement:deleteItem" }
    requirements: { _method: post|delete }