effectiveenseignentlisteenseignenteducationsportif_edit:
    path:     /Modifier
    defaults: { _controller: "SiseCoreBundle:EffectiveenseignentListeenseignenteducationsportif:edit" }

effectiveenseignentlisteenseignenteducationsportif_list:
    path:     /list
    defaults: { _controller: "SiseCoreBundle:EffectiveenseignentListeenseignenteducationsportif:list" }

effectiveenseignentlisteenseignenteducationsportif_update:
    path:     /{codeetab}/{codetypeetab}/Modif
    defaults: { _controller: "SiseCoreBundle:EffectiveenseignentListeenseignenteducationsportif:update" }
    requirements: { _method: post|put }
effectiveenseignentlisteenseignenteducationsportif_form:
    path:     /form
    defaults: { _controller: "SiseCoreBundle:EffectiveenseignentListeenseignenteducationsportif:item" }
effectiveenseignentlisteenseignenteducationsportif_deleteItem:
    path:     /deleteItem
    defaults: { _controller: "SiseCoreBundle:EffectiveenseignentListeenseignenteducationsportif:deleteItem" }
    requirements: { _method: post|delete }