effectiveenseignentheureenseignent_list:
    path:     /list
    defaults: { _controller: "SiseCoreBundle:EffectiveenseignentHeureenseignent:index" }

effectiveenseignentheureenseignent_edit:
    path:     /edit
    defaults: { _controller: "SiseCoreBundle:EffectiveenseignentHeureenseignent:edit" }

effectiveenseignentheureenseignent_update:
    path:     /update
    defaults: { _controller: "SiseCoreBundle:EffectiveenseignentHeureenseignent:update" }
    requirements: { _method: post|put }
