effectiveenseignenttypetravail_list:
    path:     /list
    defaults: { _controller: "SiseCoreBundle:EffectiveenseignentTypetravail:index" }

effectiveenseignenttypetravail_edit:
    path:     /edit
    defaults: { _controller: "SiseCoreBundle:EffectiveenseignentTypetravail:edit" }

effectiveenseignenttypetravail_update:
    path:    /update
    defaults: { _controller: "SiseCoreBundle:EffectiveenseignentTypetravail:update" }
    requirements: { _method: post|put }
