effectifelevereussifin9technique_edit:
    path:     /modifier
    defaults: { _controller: "SiseCoreBundle:EffectifeleveReussifin9technique:edit" }

effectifelevereussifin9technique_list:
    path:     /list
    defaults: { _controller: "SiseCoreBundle:EffectifeleveReussifin9technique:list" }

effectifelevereussifin9technique_update:
    path:     /{codeetab}/{codetypeetab}/Modif
    defaults: { _controller: "SiseCoreBundle:EffectifeleveReussifin9technique:update" }
    requirements: { _method: post|put|get }

effectifelevereussifin9technique_delete:
    path:     /{id}/delete
    defaults: { _controller: "SiseCoreBundle:EffectifeleveReussifin9technique:delete" }
    requirements: { _method: post|delete }