effectiveenseignentlisteremplacementprovisoire_list:
    path:     /list
    defaults: { _controller: "SiseCoreBundle:EffectiveenseignentListeremplacementprovisoire:index" }

effectiveenseignentlisteremplacementprovisoire_edit:
    path:     /edit
    defaults: { _controller: "SiseCoreBundle:EffectiveenseignentListeremplacementprovisoire:edit" }

effectiveenseignentlisteremplacementprovisoire_update:
    path:     /update
    defaults: { _controller: "SiseCoreBundle:EffectiveenseignentListeremplacementprovisoire:update" }
    requirements: { _method: post|put }
