effectiveeleverepartionelevelieuhabitation_edit:
    path:     /modifier
    defaults: { _controller: "SiseCoreBundle:EffectiveeleveRepartioneleveLieuhabitation:edit" }

effectiveeleverepartionelevelieuhabitation_list:
    path:     /list
    defaults: { _controller: "SiseCoreBundle:EffectiveeleveRepartioneleveLieuhabitation:list" }

effectiveeleverepartionelevelieuhabitation_update:
    path:     /{codeetab}/{codetypeetab}/Modif
    defaults: { _controller: "SiseCoreBundle:EffectiveeleveRepartioneleveLieuhabitation:update" }
    requirements: { _method: post|put }
effectiveeleverepartionelevelieuhabitation_form:
    path:     /form
    defaults: { _controller: "SiseCoreBundle:EffectiveeleveRepartioneleveLieuhabitation:item" }
effectiveeleverepartionelevelieuhabitation_deleteItem:
    path:     /deleteItem
    defaults: { _controller: "SiseCoreBundle:EffectiveeleveRepartioneleveLieuhabitation:deleteItem" }
    requirements: { _method: post|delete }
