effectiveelevelisteelevehandicap_edit:
    path:     /modifier
    defaults: { _controller: "SiseCoreBundle:EffectiveeleveListeelevehandicap:edit" }

effectiveelevelisteelevehandicap_list:
    path:     /list
    defaults: { _controller: "SiseCoreBundle:EffectiveeleveListeelevehandicap:list" }

effectiveelevelisteelevehandicap_update:
    path:     /{codeetab}/{codetypeetab}/Modif
    defaults: { _controller: "SiseCoreBundle:EffectiveeleveListeelevehandicap:update" }
    requirements: { _method: post|put }
effectiveelevelisteelevehandicap_form:
    path:     /form
    defaults: { _controller: "SiseCoreBundle:EffectiveeleveListeelevehandicap:item" }
effectiveelevelisteelevehandicap_deleteItem:
    path:     /deleteItem
    defaults: { _controller: "SiseCoreBundle:EffectiveeleveListeelevehandicap:deleteItem" }
    requirements: { _method: post|delete }