effectiveenseignentgradeheuretravail_list:
    path:     /
    defaults: { _controller: "SiseCoreBundle:EffectiveenseignentGradeheuretravail:index" }

effectiveenseignentgradeheuretravail_edit:
    path:    /edit
    defaults: { _controller: "SiseCoreBundle:EffectiveenseignentGradeheuretravail:edit" }

effectiveenseignentgradeheuretravail_update:
    path:     /update
    defaults: { _controller: "SiseCoreBundle:EffectiveenseignentGradeheuretravail:update" }
    requirements: { _method: post|put }
