effectifelevelisteeleveexeclus_edit:
    path:     /modifier
    defaults: { _controller: "SiseCoreBundle:EffectifeleveListeeleveexeclus:edit" }

effectifelevelisteeleveexeclus_list:
    path:     /list
    defaults: { _controller: "SiseCoreBundle:EffectifeleveListeeleveexeclus:list" }

effectifelevelisteeleveexeclus_update:
    path:     /{codeetab}/{codetypeetab}/Modif
    defaults: { _controller: "SiseCoreBundle:EffectifeleveListeeleveexeclus:update" }
    requirements: { _method: post|put }
effectifelevelisteeleveexeclus_form:
    path:     /form
    defaults: { _controller: "SiseCoreBundle:EffectifeleveListeeleveexeclus:item" }
effectifelevelisteeleveexeclus_delete:
    path:     /{id}/delete
    defaults: { _controller: "SiseCoreBundle:EffectifeleveListeeleveexeclus:delete" }
    requirements: { _method: post|delete }
effectifelevelisteeleveexeclus_deleteItem:
    path:     /deleteItem
    defaults: { _controller: "SiseCoreBundle:EffectifeleveListeeleveexeclus:deleteItem" }
    requirements: { _method: post|delete }