etablissementcycleenseignement:
    path:     /
    defaults: { _controller: "SiseCoreBundle:EtablissementCycleenseignement:index" }

etablissementcycleenseignement_show:
    path:     /{id}/show
    defaults: { _controller: "SiseCoreBundle:EtablissementCycleenseignement:show" }

etablissementcycleenseignement_new:
    path:     /new
    defaults: { _controller: "SiseCoreBundle:EtablissementCycleenseignement:new" }

etablissementcycleenseignement_create:
    path:     /create
    defaults: { _controller: "SiseCoreBundle:EtablissementCycleenseignement:create" }
    requirements: { _method: post }

etablissementcycleenseignement_edit:
    path:     /{codetypeetab}/{codeetab}/edit
    defaults: { _controller: "SiseCoreBundle:EtablissementCycleenseignement:edit" }

etablissementcycleenseignement_update:
    path:     /{codetypeetab}/{codeetab}/update
    defaults: { _controller: "SiseCoreBundle:EtablissementCycleenseignement:update" }
    requirements: { _method: post|put }

etablissementcycleenseignement_delete:
    path:     /{id}/delete
    defaults: { _controller: "SiseCoreBundle:EtablissementCycleenseignement:delete" }
    requirements: { _method: post|delete }
