etablissementficheetablissement:
    path:     /
    defaults: { _controller: "SiseCoreBundle:EtablissementFicheetablissement:index" }

etablissementficheetablissement_edit:
    path:     /{codetypeetab}/{codeetab}/edit
    defaults: { _controller: "SiseCoreBundle:EtablissementFicheetablissement:edit" }

etablissementficheetablissement_update:
    path:     /{codetypeetab}/{codeetab}/update
    defaults: { _controller: "SiseCoreBundle:EtablissementFicheetablissement:update" }
    requirements: { _method: post|put }

etablissementficheetablissement_export:
    path:     /_export
    defaults: { _controller: "SiseCoreBundle:EtablissementFicheetablissement:export" }