infrastructureequipementcategorie_edit:
    path:     /Modifier
    defaults: { _controller: "SiseCoreBundle:InfrastructureTypecategorieespace:edit" }

infrastructureequipementcategorie_list:
    path:     /list
    defaults: { _controller: "SiseCoreBundle:InfrastructureTypecategorieespace:list" }

infrastructureequipementcategorie_update:
    path:     /{codeetab}/{codetypeetab}/Modif
    defaults: { _controller: "SiseCoreBundle:InfrastructureTypecategorieespace:update" }
    requirements: { _method: post|put }

infrastructureequipementcategorie_delete:
    path:     /{id}/delete
    defaults: { _controller: "SiseCoreBundle:InfrastructureTypecategorieespace:delete" }
    requirements: { _method: post|delete }
