infrastructuretypecategorieespace_edit:
    path:     /Modifier
    defaults: { _controller: "SiseCoreBundle:InfrastructureEquipementCategorie:edit" }

infrastructuretypecategorieespace_list:
    path:     /list
    defaults: { _controller: "SiseCoreBundle:InfrastructureEquipementCategorie:list" }

infrastructuretypecategorieespace_update:
    path:     /{codeetab}/{codetypeetab}/Modif
    defaults: { _controller: "SiseCoreBundle:InfrastructureEquipementCategorie:update" }
    requirements: { _method: post|put }

infrastructuretypecategorieespace_delete:
    path:     /{id}/delete
    defaults: { _controller: "SiseCoreBundle:InfrastructureEquipementCategorie:delete" }
    requirements: { _method: post|delete }
