infrastructureequipementcategorie_edit:
    path:     /modifier
    defaults: { _controller: "SiseCoreBundle:InfrastructureEquipementCategorie:edit" }

infrastructureequipementcategorie_list:
    path:     /list
    defaults: { _controller: "SiseCoreBundle:InfrastructureEquipementCategorie:list" }

infrastructureequipementcategorie_update:
    path:     /{codeetab}/{codetypeetab}/Modif
    defaults: { _controller: "SiseCoreBundle:InfrastructureEquipementCategorie:update" }
    requirements: { _method: post|put }

infrastructureequipementcategorie_delete:
    path:     /{id}/delete
    defaults: { _controller: "SiseCoreBundle:InfrastructureEquipementCategorie:delete" }
    requirements: { _method: post|delete }
