mouvementelevelisteelevessepareavantconseilclasse_edit:
    path:     /modifier
    defaults: { _controller: "SiseCoreBundle:MouvementeleveListeelevessepareavantconseilclasse:edit" }

mouvementelevelisteelevessepareavantconseilclasse_list:
    path:     /list
    defaults: { _controller: "SiseCoreBundle:MouvementeleveListeelevessepareavantconseilclasse:list" }

mouvementelevelisteelevessepareavantconseilclasse_update:
    path:     /{codeetab}/{codetypeetab}/Modif
    defaults: { _controller: "SiseCoreBundle:MouvementeleveListeelevessepareavantconseilclasse:update" }
    requirements: { _method: post|put }
mouvementelevelisteelevessepareavantconseilclasse_form:
    path:     /form
    defaults: { _controller: "SiseCoreBundle:MouvementeleveListeelevessepareavantconseilclasse:item" }
mouvementelevelisteelevessepareavantconseilclasse_deleteItem:
    path:     /deleteItem
    defaults: { _controller: "SiseCoreBundle:MouvementeleveListeelevessepareavantconseilclasse:deleteItem" }
    requirements: { _method: post|delete }