mouvementeleverecapmouvmenteleve_list:
    path:     /list
    defaults: { _controller: "SiseCoreBundle:MouvementeleveRecapmouvmenteleve:index" }

mouvementeleverecapmouvmenteleve_edit:
    path:     /edit
    defaults: { _controller: "SiseCoreBundle:MouvementeleveRecapmouvmenteleve:edit" }

mouvementeleverecapmouvmenteleve_update:
    path:     /update
    defaults: { _controller: "SiseCoreBundle:MouvementeleveRecapmouvmenteleve:update" }
    requirements: { _method: post|put }
