statElev:
    path:     /{codepack}/statElev{trailingSlash}
    defaults: { _controller: "SiseCoreBundle:NomenclatureQuestionnaire:statElev", trailingSlash : "/" }
    requirements: { trailingSlash : "[/]{0,1}" }
statElev_show:
    path:     /{id}/show
    defaults: { _controller: "SiseCoreBundle:NomenclatureQuestionnaire:show" }

statElev_new:
    path:     /new
    defaults: { _controller: "SiseCoreBundle:NomenclatureQuestionnaire:new" }

statElev_create:
    path:     /create
    defaults: { _controller: "SiseCoreBundle:NomenclatureQuestionnaire:create" }
    requirements: { _method: post }

statElev_delete:
    path:     /{id}/delete
    defaults: { _controller: "SiseCoreBundle:NomenclatureQuestionnaire:delete" }
    requirements: { _method: post|delete }
