statElev:
    path:     /{codepack}/statElev{trailingSlash}
    defaults: { _controller: "SiseCoreBundle:NomenclatureQuestionnaire:statElev", trailingSlash : "/" }
    requirements: { trailingSlash : "[/]{0,1}" }
statElev_show:
    path:     /{id}/show
    defaults: { _controller: "SiseCoreBundle:NomenclatureQuestionnaire:show" }

statElev_new:
    path:     /new
    defaults: { _controller: "SiseCoreBundle:NomenclatureQuestionnaire:new" }

statElev_create:
    path:     /create
    defaults: { _controller: "SiseCoreBundle:NomenclatureQuestionnaire:create" }
    requirements: { _method: post }

statElev_edit:
    path:     /{table}/edit
    defaults: { _controller: "SiseCoreBundle:NomenclatureQuestionnaire:edit" }

statElev_listStat:
    path:     /{table}/stat
    defaults: { _controller: "SiseCoreBundle:NomenclatureQuestionnaire:listStat" }

statElev_update:
    path:     /{table}/{codeetab}/{codetypeetab}/update
    defaults: { _controller: "SiseCoreBundle:NomenclatureQuestionnaire:update" }
    requirements: { _method: post|put }

statElev_delete:
    path:     /{id}/delete
    defaults: { _controller: "SiseCoreBundle:NomenclatureQuestionnaire:delete" }
    requirements: { _method: post|delete }
