nomenclaturerecensement:
    path:     /
    defaults: { _controller: "SiseCoreBundle:NomenclatureRecensement:index" }

nomenclaturerecensement_show:
    path:     /{id}/show
    defaults: { _controller: "SiseCoreBundle:NomenclatureRecensement:show" }

nomenclaturerecensement_new:
    path:     /new
    defaults: { _controller: "SiseCoreBundle:NomenclatureRecensement:new" }

nomenclaturerecensement_create:
    path:     /create
    defaults: { _controller: "SiseCoreBundle:NomenclatureRecensement:create" }
    requirements: { _method: post }

nomenclaturerecensement_edit:
    path:     /{id}/edit
    defaults: { _controller: "SiseCoreBundle:NomenclatureRecensement:edit" }

nomenclaturerecensement_update:
    path:     /{id}/update
    defaults: { _controller: "SiseCoreBundle:NomenclatureRecensement:update" }
    requirements: { _method: post|put }

nomenclaturerecensement_delete:
    path:     /{id}/delete
    defaults: { _controller: "SiseCoreBundle:NomenclatureRecensement:delete" }
    requirements: { _method: post|delete }


nomenclaturerecensement_export:
    path:     /_export
    defaults: { _controller: "SiseCoreBundle:NomenclatureRecensement:export" }