orientationfilieresportversgeneraledeuxieme_list:
    path:     /list
    defaults: { _controller: "SiseCoreBundle:OrientationFilieresportversgeneraledeuxieme:index" }

orientationfilieresportversgeneraledeuxieme_edit:
    path:     /edit
    defaults: { _controller: "SiseCoreBundle:OrientationFilieresportversgeneraledeuxieme:edit" }

orientationfilieresportversgeneraledeuxieme_update:
    path:     /update
    defaults: { _controller: "SiseCoreBundle:OrientationFilieresportversgeneraledeuxieme:update" }
    requirements: { _method: post|put }

