orientationeleveredoublantdeuxiemeannee_list:
    path:     /list
    defaults: { _controller: "SiseCoreBundle:OrientationEleveredoublantdeuxiemeannee:index" }

orientationeleveredoublantdeuxiemeannee_edit:
    path:     /edit
    defaults: { _controller: "SiseCoreBundle:OrientationEleveredoublantdeuxiemeannee:edit" }

orientationeleveredoublantdeuxiemeannee_update:
    path:     /update
    defaults: { _controller: "SiseCoreBundle:OrientationEleveredoublantdeuxiemeannee:update" }
    requirements: { _method: post|put }

