orientationelevereussitroisiemeannee_list:
    path:     /list
    defaults: { _controller: "SiseCoreBundle:OrientationElevereussitroisiemeannee:index" }

orientationelevereussitroisiemeannee_edit:
    path:     /edit
    defaults: { _controller: "SiseCoreBundle:OrientationElevereussitroisiemeannee:edit" }

orientationelevereussitroisiemeannee_update:
    path:     /update
    defaults: { _controller: "SiseCoreBundle:OrientationElevereussitroisiemeannee:update" }
    requirements: { _method: post|put }

