orientationeleveredoublanttroisiemeannee_list:
    path:     /list
    defaults: { _controller: "SiseCoreBundle:OrientationEleveredoublanttroisiemeannee:index" }

orientationeleveredoublanttroisiemeannee_edit:
    path:     /edit
    defaults: { _controller: "SiseCoreBundle:OrientationEleveredoublanttroisiemeannee:edit" }

orientationeleveredoublanttroisiemeannee_update:
    path:     /update
    defaults: { _controller: "SiseCoreBundle:OrientationEleveredoublanttroisiemeannee:update" }
    requirements: { _method: post|put }
