orientationfilieresportversgeneraletroisieme_list:
    path:     /list
    defaults: { _controller: "SiseCoreBundle:OrientationFilieresportversgeneraletroisieme:index" }

orientationfilieresportversgeneraletroisieme_new:
    path:     /new
    defaults: { _controller: "SiseCoreBundle:OrientationFilieresportversgeneraletroisieme:new" }

orientationfilieresportversgeneraletroisieme_edit:
    path:     /edit
    defaults: { _controller: "SiseCoreBundle:OrientationFilieresportversgeneraletroisieme:edit" }

orientationfilieresportversgeneraletroisieme_update:
    path:     /update
    defaults: { _controller: "SiseCoreBundle:OrientationFilieresportversgeneraletroisieme:update" }
    requirements: { _method: post|put }