orientationelevereussideuxiemeannee_list:
    path:     /list
    defaults: { _controller: "SiseCoreBundle:OrientationElevereussideuxiemeannee:index" }

orientationelevereussideuxiemeannee_edit:
    path:     /edit
    defaults: { _controller: "SiseCoreBundle:OrientationElevereussideuxiemeannee:edit" }

orientationelevereussideuxiemeannee_update:
    path:     /update
    defaults: { _controller: "SiseCoreBundle:OrientationElevereussideuxiemeannee:update" }
    requirements: { _method: post|put }
