orientationfilieresport_list:
    path:     /list
    defaults: { _controller: "SiseCoreBundle:OrientationFilieresport:index" }

orientationfilieresport_edit:
    path:     /edit
    defaults: { _controller: "SiseCoreBundle:OrientationFilieresport:edit" }

orientationfilieresport_update:
    path:     /update
    defaults: { _controller: "SiseCoreBundle:OrientationFilieresport:update" }
    requirements: { _method: post|put }
