orientationelevereussideuxiemeannee_list:
    path:     /list
    defaults: { _controller: "SiseCoreBundle:OrientationElevereussideuxiemeannee:index" }

orientationelevereussideuxiemeannee_show:
    path:     /{id}/show
    defaults: { _controller: "SiseCoreBundle:OrientationElevereussideuxiemeannee:show" }

orientationelevereussideuxiemeannee_new:
    path:     /new
    defaults: { _controller: "SiseCoreBundle:OrientationElevereussideuxiemeannee:new" }

orientationelevereussideuxiemeannee_create:
    path:     /create
    defaults: { _controller: "SiseCoreBundle:OrientationElevereussideuxiemeannee:create" }
    requirements: { _method: post }

orientationelevereussideuxiemeannee_edit:
    path:     /edit
    defaults: { _controller: "SiseCoreBundle:OrientationElevereussideuxiemeannee:edit" }

orientationelevereussideuxiemeannee_update:
    path:     /{id}/update
    defaults: { _controller: "SiseCoreBundle:OrientationElevereussideuxiemeannee:update" }
    requirements: { _method: post|put }

orientationelevereussideuxiemeannee_delete:
    path:     /{id}/delete
    defaults: { _controller: "SiseCoreBundle:OrientationElevereussideuxiemeannee:delete" }
    requirements: { _method: post|delete }
