parametrereglegestionquestionnaire:
    path:     /
    defaults: { _controller: "SiseCoreBundle:ParametreReglegestionquestionnaire:index" }

parametrereglegestionquestionnaire_show:
    path:     /{id}/show
    defaults: { _controller: "SiseCoreBundle:ParametreReglegestionquestionnaire:show" }

parametrereglegestionquestionnaire_new:
    path:     /new
    defaults: { _controller: "SiseCoreBundle:ParametreReglegestionquestionnaire:new" }

parametrereglegestionquestionnaire_create:
    path:     /create
    defaults: { _controller: "SiseCoreBundle:ParametreReglegestionquestionnaire:create" }
    requirements: { _method: post }

parametrereglegestionquestionnaire_edit:
    path:     /{id}/edit
    defaults: { _controller: "SiseCoreBundle:ParametreReglegestionquestionnaire:edit" }

parametrereglegestionquestionnaire_update:
    path:     /{id}/update
    defaults: { _controller: "SiseCoreBundle:ParametreReglegestionquestionnaire:update" }
    requirements: { _method: post|put }

parametrereglegestionquestionnaire_delete:
    path:     /{id}/delete
    defaults: { _controller: "SiseCoreBundle:ParametreReglegestionquestionnaire:delete" }
    requirements: { _method: post|delete }
