sise_core_homepage:
    path:     /
    defaults: { _controller: SiseCoreBundle:Default:index }
sise_core_search:
    path:     /search
    defaults: { _controller: SiseCoreBundle:Default:search }
sise_core_selectCodeRec:
    path:     /selectCodeRec
    defaults: { _controller: SiseCoreBundle:Default:selectCodeRec }
sise_core_setCodeRec:
    path:     /setCodeRec
    defaults: { _controller: SiseCoreBundle:Default:setCodeRec }
sise_core_listEntities:
    path:     /listEntities
    defaults: { _controller: SiseCoreBundle:Default:listEntities }
sise_core_getList:
    path:     /getList
    defaults: { _controller: SiseCoreBundle:Default:getList }
sise_core_getListMulti:
    path:     /getListMulti
    defaults: { _controller: SiseCoreBundle:Default:getListMulti }
SiseCoreBundle_StatEleve:
    resource: "routing/nomenclaturequestionnaire.yml"
    prefix:   /stat
SiseCoreBundle_effectifelevedemiresidant:
    resource: "routing/effectifelevedemiresidant.yml"
    prefix:   /stat/effectifelevedemiresidant
SiseCoreBundle_effectifeleveelevedomainsousdomain:
    resource: "routing/effectifeleveelevedomainsousdomain.yml"
    prefix:   /stat/effectifeleveelevedomainsousdomain
SiseCoreBundle_effectiveeleveniveauscolaireanneenaissance:
    resource: "routing/effectiveeleveniveauscolaireanneenaissance.yml"
    prefix:   /stat/effectiveeleveniveauscolaireanneenaissance
SiseCoreBundle_effectiveeleverepartionelevelieuhabitatione:
    resource: "routing/effectiveeleverepartionelevelieuhabitatione.yml"
    prefix:   /stat/effectiveeleverepartionelevelieuhabitation
Coreblog_NomenclatureEtablissement:
    resource: "routing/nomenclatureetablissement.yml"
    prefix: /NomenclatureEtablissement
Coreblog_NomenclatureCycleenseignement:
    resource: "routing/nomenclaturecycleenseignement.yml"
    prefix: /NomenclatureCycleenseignement
Siseblog_EtablissementFicheetablissement:
    resource: "routing/etablissementficheetablissement.yml"
    prefix: /EtablissementFicheetablissement