sise_core_homepage:
    path:     /
    defaults: { _controller: SiseCoreBundle:Default:index }
sise_core_search:
    path:     /search
    defaults: { _controller: SiseCoreBundle:Default:search }
sise_core_selectCodeRec:
    path:     /selectCodeRec
    defaults: { _controller: SiseCoreBundle:Default:selectCodeRec }
sise_core_setCodeRec:
    path:     /setCodeRec
    defaults: { _controller: SiseCoreBundle:Default:setCodeRec }
sise_core_listEntities:
    path:     /listEntities
    defaults: { _controller: SiseCoreBundle:Default:listEntities }
sise_core_getList:
    path:     /getList
    defaults: { _controller: SiseCoreBundle:Default:getList }
sise_core_getListMulti:
    path:     /getListMulti
    defaults: { _controller: SiseCoreBundle:Default:getListMulti }
SiseCoreBundle_StatEleve:
    resource: "routing/nomenclaturequestionnaire.yml"
    prefix:   /stat
SiseCoreBundle_effectifelevedemiresidant:
    resource: "routing/effectifelevedemiresidant.yml"
    prefix:   /stat/effectifelevedemiresidant
SiseCoreBundle_effectifeleveelevedomainsousdomain:
    resource: "routing/effectifeleveelevedomainsousdomain.yml"
    prefix:   /stat/effectifeleveelevedomainsousdomain
SiseCoreBundle_effectiveeleveniveauscolaireanneenaissance:
    resource: "routing/effectiveeleveniveauscolaireanneenaissance.yml"
    prefix:   /stat/effectiveeleveniveauscolaireanneenaissance
SiseCoreBundle_effectiveeleverepartionelevelieuhabitatione:
    resource: "routing/effectiveeleverepartionelevelieuhabitation.yml"
    prefix:   /stat/effectiveeleverepartionelevelieuhabitation
SiseCoreBundle_effectifelevefilstravailleuretrangercycleenseignement:
    resource: "routing/effectifelevefilstravailleuretrangercycleenseignement.yml"
    prefix:   /stat/effectifelevefilstravailleuretrangercycleenseignement
SiseCoreBundle_effectiveeleveniveauscolaire:
    resource: "routing/effectiveeleveniveauscolaire.yml"
    prefix:   /stat/effectiveeleveniveauscolaire
SiseCoreBundle_effectiveeleveeleveeablissementprivee:
    resource: "routing/effectiveeleveeleveeablissementprivee.yml"
    prefix:   /stat/effectiveeleveeleveeablissementprivee
SiseCoreBundle_effectifelevegenreanneenaissance:
    resource: "routing/effectifelevegenreanneenaissance.yml"
    prefix:   /stat/effectifelevegenreanneenaissance
SiseCoreBundle_effectifelevenouveauhuitiemetechnique:
    resource: "routing/effectifelevenouveauhuitiemetechnique.yml"
    prefix:   /stat/effectifelevenouveauhuitiemetechnique
SiseCoreBundle_effectifeleveresultatconcoureducationbase:
    resource: "routing/effectifeleveresultatconcoureducationbase.yml"
    prefix:   /stat/effectifeleveresultatconcoureducationbase
SiseCoreBundle_effectifeleveresidantboursiercycleenseignement:
    resource: "routing/effectifeleveresidantboursiercycleenseignement.yml"
    prefix:   /stat/effectifeleveresidantboursiercycleenseignement
SiseCoreBundle_effectiveeleveeleveetranger:
    resource: "routing/effectiveeleveeleveetranger.yml"
    prefix:   /stat/effectiveeleveeleveetranger
SiseCoreBundle_effectiveeleveelevenouveauclasspreparatoire:
    resource: "routing/effectiveeleveelevenouveauclasspreparatoire.yml"
    prefix:   /stat/effectiveeleveelevenouveauclasspreparatoire
SiseCoreBundle_effectiveelevelisteelevehandicap:
    resource: "routing/effectiveelevelisteelevehandicap.yml"
    prefix:   /stat/effectiveelevelisteelevehandicap
SiseCoreBundle_effectifelevefilierematiere:
    resource: "routing/effectifelevefilierematiere.yml"
    prefix:   /stat/effectifelevefilierematiere
SiseCoreBundle_effectiveelevenouveauseptiemeannee:
    resource: "routing/effectiveelevenouveauseptiemeannee.yml"
    prefix:   /stat/effectiveelevenouveauseptiemeannee
SiseCoreBundle_effectifelevereussifin9technique:
    resource: "routing/effectifelevereussifin9technique.yml"
    prefix:   /stat/effectifelevereussifin9technique
SiseCoreBundle_effectifelevevenant9emetechnique:
    resource: "routing/effectifelevevenant9emetechnique.yml"
    prefix:   /stat/effectifelevevenant9emetechnique
Coreblog_NomenclatureEtablissement:
    resource: "routing/nomenclatureetablissement.yml"
    prefix: /NomenclatureEtablissement
Coreblog_NomenclatureCycleenseignement:
    resource: "routing/nomenclaturecycleenseignement.yml"
    prefix: /NomenclatureCycleenseignement
Siseblog_EtablissementFicheetablissement:
    resource: "routing/etablissementficheetablissement.yml"
    prefix: /EtablissementFicheetablissement
Siseblog_EffectifeleveListeelevedeplacerversautreetablissement:
    resource: "routing/effectifelevelisteelevedeplacerversautreetablissement.yml"
    prefix: /EffectifeleveListeelevedeplacerversautreetablissement
Siseblog_NomenclatureRecensement:
    resource: "routing/nomenclaturerecensement.yml"
    prefix: /NomenclatureRecensement
Siseblog_EffectifeleveListeeleveemmenagerdesonetablissement:
    resource: "routing/effectifelevelisteeleveemmenagerdesonetablissement.yml"
    prefix: /EffectifeleveListeeleveemmenagerdesonetablissement
Siseblog_EffectifeleveListeeleveexeclus:
    resource: "routing/effectifelevelisteeleveexeclus.yml"
    prefix: /EffectifeleveListeeleveexeclus
Siseblog_MouvementeleveListeelevessepareavantconseilclasse:
    resource: "routing/mouvementelevelisteelevessepareavantconseilclasse.yml"
    prefix: /MouvementeleveListeelevessepareavantconseilclasse
Siseblog_MouvementeleveRecapmouvmenteleve:
    resource: "routing/mouvementeleverecapmouvmenteleve.yml"
    prefix: /MouvementeleveRecapmouvmenteleve
Siseblog_OrientationFilieresport:
    resource: "routing/OrientationFilieresport.yml"
    prefix: /OrientationFilieresport
Siseblog_OrientationFilieresportversgeneraledeuxieme:
    resource: "routing/OrientationFilieresportversgeneraledeuxieme.yml"
    prefix: /OrientationFilieresportversgeneraledeuxieme