services:
#    sise_user.example:
#        class: Sise\Bundle\UserBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
    sise_user.password_resetting:
        class: Sise\Bundle\UserBundle\EventListener\PasswordResettingListener
        arguments: [@router]
        tags:
            - { name: kernel.event_subscriber }
    sise_user.registration.form.type:
        class: Sise\Bundle\UserBundle\Form\Type\RegistrationFormType
        tags:
            - { name: form.type, alias: sise_user_registration }
    sise_user.relatedItems.form.type:
        class: Sise\Bundle\UserBundle\Form\Type\relatedItemsFormType
        tags:
            - { name: form.type, alias: sise_user_relatedItems }
    sise_user.group.form.type:
         class: Sise\Bundle\UserBundle\Form\Type\GroupFormType
         tags:
             - { name: form.type, alias: sise_user_group }
    redirect.after.login:
        class: Sise\Bundle\UserBundle\Handler\AfterLoginRedirection
        arguments: [@router, @doctrine.orm.entity_manager]
    redirect.after.logout:
        class: Sise\Bundle\UserBundle\Handler\AfterLogoutRedirection
        arguments: [@router, @security.context]
    sise_user_activity_listener:
      class: Sise\Bundle\UserBundle\EventListener\ActivityListener
      arguments: [@security.context, @doctrine.orm.entity_manager]
      tags:
        - { name: kernel.event_listener, event: kernel.controller, method: onCoreController }