services:
#    sise_user.example:
#        class: Sise\Bundle\UserBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
    sise_user.password_resetting:
        class: Sise\Bundle\UserBundle\EventListener\PasswordResettingListener
        arguments: [@router]
        tags:
            - { name: kernel.event_subscriber }
    sise_user.registration.form.type:
        class: Sise\Bundle\UserBundle\Form\Type\RegistrationFormType
        tags:
            - { name: form.type, alias: sise_user_registration }
    redirect.after.login:
        class: Sise\Bundle\UserBundle\Handler\AfterLoginRedirection
        arguments: [@router]
    redirect.after.logout:
        class: Sise\Bundle\UserBundle\Handler\AfterLogoutRedirection
        arguments: [@router, @security.context]