<?php
/**
 * Created by PhpStorm.
 * User: hp
 * Date: 23/12/2014
 * Time: 12:31
 */
namespace Sise\Bundle\CoreBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * EtablissementRecensementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EffectiveeleveRepartioneleveLieuhabitationRepository extends EntityRepository
{
}
