<?php

namespace Sise\Bundle\CoreBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * EtablissementRecensementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EtablissementRecensementRepository extends EntityRepository
{
}
