<?php

namespace Sise\Bundle\CoreBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * NomenclatureDistanceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NomenclatureDistanceRepository extends EntityRepository
{
}
