<?php

namespace Sise\Bundle\CoreBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CoreProjectRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CoreProjectRepository extends EntityRepository
{
}
