<?php

namespace Sise\Bundle\CoreBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * NomenclatureValueexogeneRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NomenclatureValueexogeneRepository extends EntityRepository
{
}
